name: Grenades
main: tc.oc.grenades.GrenadesPlugin
version: ${project.version}
author: Overcast Network

permissions:
  grenades.use:
    description: Allows the player to use grenades
    default: false
